# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CGVirtualPOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CGVirtualPOS
  
  pod 'Alamofire','4.0'
  pod 'AlamofireImage','3.1'
  pod 'ObjectMapper'
  pod 'PromiseKit','4.5.2'
  pod 'ReachabilitySwift','~> 4.3.0'
  pod 'SwiftyJSON','~> 4.0.0'
  pod 'SwiftMessages'
  pod 'XCGLogger', '~> 6.0.4'
  pod 'TransitionableTab', '~> 0.1.2'
  pod 'DropDown'
#  pod 'JBTabBarAnimation'
  pod 'IQKeyboardManagerSwift', '>= 5.0.0'
  
end
